"use client";

import { useState, useRef, useEffect } from "react";
import { ArrowUpIcon, StopIcon } from "@heroicons/react/24/solid";

interface Props {
  onSend: (input: string) => void;
  onStop: () => void;
  streaming: boolean;
}

export function ChatInput({ onSend, onStop, streaming }: Props) {
  const [input, setInput] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (!streaming && textareaRef.current) {
      textareaRef.current.focus();
    }
  }, [streaming]);

  const handleSubmit = () => {
    if (streaming) {
      onStop();
    } else if (input.trim()) {
      onSend(input.trim());
      setInput("");
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  useEffect(() => {
    const el = textareaRef.current;
    if (el) {
      el.style.height = "auto";
      el.style.height = Math.min(el.scrollHeight, 200) + "px";
    }
  }, [input]);

  const canSend = input.trim().length > 0;

  return (
    <div className="px-4 pb-4 pt-2">
      <div className="mx-auto max-w-3xl">
        <div className="relative flex items-end rounded-2xl border border-zinc-700 bg-zinc-800 shadow-lg focus-within:border-zinc-600">
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask anything"
            rows={1}
            disabled={streaming}
            className="max-h-[200px] min-h-[52px] flex-1 resize-none bg-transparent px-4 py-3.5 pr-14 text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none disabled:opacity-60"
          />
          <div className="absolute bottom-2.5 right-2.5">
            <button
              onClick={handleSubmit}
              className={`flex h-8 w-8 items-center justify-center rounded-full transition-colors ${
                streaming
                  ? "bg-zinc-100 text-zinc-900 hover:bg-zinc-200"
                  : canSend
                  ? "bg-zinc-100 text-zinc-900 hover:bg-zinc-200"
                  : "bg-zinc-700 text-zinc-500 cursor-not-allowed"
              }`}
              disabled={!streaming && !canSend}
            >
              {streaming ? (
                <StopIcon className="h-3.5 w-3.5" />
              ) : (
                <ArrowUpIcon className="h-3.5 w-3.5" />
              )}
            </button>
          </div>
        </div>
        <p className="mt-2 text-center text-[10px] text-zinc-600">
          Responses are generated by AI. Verify critical findings manually.
        </p>
      </div>
    </div>
  );
}
