"use client";

import { useState, useRef, useEffect } from "react";
import { PaperAirplaneIcon, StopIcon } from "@heroicons/react/24/outline";

interface Props {
  onSend: (input: string) => void;
  onStop: () => void;
  streaming: boolean;
}

export function ChatInput({ onSend, onStop, streaming }: Props) {
  const [input, setInput] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (!streaming && textareaRef.current) {
      textareaRef.current.focus();
    }
  }, [streaming]);

  const handleSubmit = () => {
    if (streaming) {
      onStop();
    } else if (input.trim()) {
      onSend(input.trim());
      setInput("");
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  // Auto-resize textarea
  useEffect(() => {
    const el = textareaRef.current;
    if (el) {
      el.style.height = "auto";
      el.style.height = Math.min(el.scrollHeight, 200) + "px";
    }
  }, [input]);

  return (
    <div className="border-t border-zinc-800 bg-zinc-900/50 px-4 py-3">
      <div className="mx-auto flex max-w-3xl items-end gap-2">
        <textarea
          ref={textareaRef}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Ask Unixcorn AI to perform a security task..."
          rows={1}
          disabled={streaming}
          className="max-h-[200px] min-h-[40px] flex-1 resize-none rounded-lg border border-zinc-700 bg-zinc-800 px-3 py-2.5 text-sm text-zinc-100 placeholder-zinc-500 focus:border-fuchsia-600 focus:outline-none disabled:opacity-50"
        />
        <button
          onClick={handleSubmit}
          className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg transition-colors ${
            streaming
              ? "bg-red-700 text-white hover:bg-red-600"
              : "bg-fuchsia-700 text-white hover:bg-fuchsia-600"
          }`}
        >
          {streaming ? (
            <StopIcon className="h-4 w-4" />
          ) : (
            <PaperAirplaneIcon className="h-4 w-4" />
          )}
        </button>
      </div>
      <p className="mt-1.5 text-center text-[10px] text-zinc-600">
        Responses are generated by AI. Verify critical findings manually.
      </p>
    </div>
  );
}
